
#define HERO_COUNT 6

//
// None
//
#define HERO_NONE 0

//
// Lucio
//
#define HERO_LUCIO 1

//
// Mercy
//
#define HERO_MERCY 2
#define HERO_MERCY_HOLD_TIME 500

//
// Rein
//
#define HERO_REIN 3
#define REIN_SWING_STEPS (120 / OVERWATCH_MOUSE_SENSITIVITY)
// From beginning to end.  Measured 50 swings and averaged.
#define REIN_SWING_FULL_CYCLE_TIME 1842


//
// Zarya
//
#define HERO_ZARYA 4
#define OVERWATCH_MOUSE_SENSITIVITY 1.4
#define HERO_ZARYA_STEPS_MOVEDOWN1 (156 / OVERWATCH_MOUSE_SENSITIVITY)
#define HERO_ZARYA_STEPS_MOVEUP1 (105 / OVERWATCH_MOUSE_SENSITIVITY)

// MS Timing for each phase
#define HERO_ZARYA_ROCKET_HOLD_TIME 20
#define HERO_ZARYA_DOUBLE_ROCKET_HOLD_TIME 5000 // 1950 MIGHT be better
#define HERO_ZARYA_ROCKET_MOUSE_CLICK_TIME 20

// For Running Jump
#define HERO_ZARYA_ROCKET_RUNNING_TIME 75
const int16_t HERO_ZARYA_DOUBLE_ROCKET_HOLD_TIME_RUNNING = (HERO_ZARYA_ROCKET_RUNNING_TIME/4)+ HERO_ZARYA_DOUBLE_ROCKET_HOLD_TIME - (2*HERO_ZARYA_ROCKET_RUNNING_TIME)+HERO_ZARYA_ROCKET_MOUSE_CLICK_TIME+HERO_ZARYA_ROCKET_HOLD_TIME;



#define HERO_ASHE 5
#define HERO_ASHE_STEPS_BEFORE_FIRING_SHOTGUN 35
#define HORIZONTAL_360_STEPS (429 / OVERWATCH_MOUSE_SENSITIVITY)


#define HERO_BAP 6
#define HERO_BAP_TIME_BETWEEN_RECOILS 85
#define HERO_BAP_RECOIL_MOUSE_DISTANCE 100 / OVERWATCH_MOUSE_SENSITIVITY
#define HERO_BAP_TIME_FROM_LAST_RECOIL_TO_IDLE 580 - (HERO_BAP_TIME_BETWEEN_RECOILS * 2)
#define HERO_BAP_TIME_FROM_HEAL_TO_IDLE 900 + 50

char overwatchTxt[14] = {0};
int8_t selectedHero = HERO_NONE;
bool isMacMode = false;



enum sofle_layers {
    /* _M_XYZ = Mac Os, _W_XYZ = Win/Linux */
    _BASE,
    _LOWER,
    _RAISE,
    _GAME,
};

// enum my_keycodes {
//     KC_OVERWATCH_ACTION1 = 0x5dae, // 0x5daf
//     KC_OVERWATCH_ACTION2, // 0x5dae
// };

enum custom_keycodes {
    KC_OVERWATCH_ACTION1 = SAFE_RANGE,
    KC_OVERWATCH_ACTION2,
    KC_BASE,
    KC_LOWER,
    KC_RAISE,
    KC_GAME,
};
