OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes
VIA_ENABLE = no
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = no
WPM_ENABLE = no
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = custom
UNICODE_ENABLE = no

SERIAL_DRIVER = vendor
WS2812_DRIVER = vendor

DEBOUNCE_TYPE = sym_eager_pk
DEBOUNCE = 1

//MOUSEKEY_ENABLE = yes
