OLED_ENABLE = yes
OLED_DRIVER = SSD1306
ENCODER_ENABLE = yes
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
VIA_ENABLE = yes
LTO_ENABLE = yes
RGBLIGHT_ENABLE = yes
AUDIO_ENABLE = no
WPM_ENABLE = no

CUSTOM_SPLIT_TRANSPORT_SYNC = yes
